name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
            
      - name: Install dependencies
        run: npm ci

#      - name: Build dist directory
#        run: npm run build

      - name: Zip Files
        working-directory: ./dist
        run: zip -r ./module.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
        
      - name: Create Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set this to false if you want to prevent updating existing releases
          name: ${{ steps.get-version.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json,./dist/module.zip'
          tag_name: ${{ steps.get-version.outputs.version }}
